### ISSUE TITLE
Deep learning engine not found: MPI  Error  

### ISSUE THREAD

**Issue by prgawade** [deepjavalibrary/djl-serving#1351]
Description: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Deep learning engine not found: MPI  Error when we trying with below configuration with deepjavalibrary/djl-serving:0.24.0-deepspeed

Serving.properties

engine=MPI 
option.model_id=starcoderbase
option.trust_remote_code=true
option.tensor_parallel_degree=1
option.max_rolling_batch_size=32
option.rolling_batch=auto
option.output_formatter=jsonlines
option.paged_attention=false
option.enable_streaming=true
 
 
Log:
 
INFO  ModelInfo Apply per model settings:
	job_queue_size: 1000
	batch_size: 1
	max_batch_delay: 100
	max_idle_time: 60
	load_on_devices: *
	engine: MPI 
	option.entryPoint: djl_python.huggingface
	option.enable_streaming: true
	option.tensor_parallel_degree: 1
	option.max_rolling_batch_size: 32
	option.trust_remote_code: true
	option.output_formatter: jsonlines
	option.paged_attention: false
	option.rolling_batch: auto
DEBUG Engine Registering EngineProvider: MXNet
DEBUG Engine Registering EngineProvider: Python
DEBUG Engine Registering EngineProvider: MPI
DEBUG Engine Registering EngineProvider: FasterTransformer
DEBUG Engine Registering EngineProvider: DeepSpeed
DEBUG Engine Registering EngineProvider: PyTorch
DEBUG Engine Registering EngineProvider: TensorFlow
DEBUG Engine Registering EngineProvider: TensorRT
ERROR ModelServer Failed register workflow
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Deep learning engine not found: MPI 
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.IllegalArgumentException: Deep learning engine not found: MPI 
	at ai.djl.engine.Engine.getEngine(Engine.java:188) ~[api-0.23.0.jar:?]
	at ai.djl.serving.wlm.ModelInfo.getLoadOnDevices(ModelInfo.java:774) ~[wlm-0.23.0.jar:?]
	at ai.djl.serving.models.ModelManager.lambda$registerWorkflow$2(ModelManager.java:112) ~[serving-0.23.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	... 6 more
INFO  ModelServer Stopping model server.

**Comment by lanking520** [comment]
The model ID should be `bigcode/starcoderbase` ?

**Comment by frankfliu** [comment]
@prgawade 

I tried your `serving.properties` and I not able to reproduce your issue. And your log is bit suspicious:

```
	option.entryPoint: djl_python.huggingface
```

The `serving.properties` you posted in this issue may not the same as in your model.
