### ISSUE TITLE
Python engine batching functionality does not work

### ISSUE THREAD

**Issue by prgawade** [deepjavalibrary/djl-serving#775]
## Description
We have deployed a flant5 model on a Nvidia GPU infrastructure with the following serving.properties

engine=Python
option.entryPoint=djl_python.deepspeed
option.task=text2text-generation
option.dtype=int8
option.device_map=balanced
batch_size=2
max_batch_delay=1

Model works fine for a single request but for concurrent users it starts throwing HTTP 400 error

### Expected Behavior
Dynamic batching should be supported for DJL serving 

### Error Message
{
  "code": 400,
  "type": "TranslateException",
  "message": "Batch output size mismatch, expected: 2, actual: 1"
}

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Download flant5-xl model from hugging face repository to the local disk
2. Update serving.properties
3. Deploy deepjavalibrary/djl-serving:0.22.1-deepspeed on the kubernetes environment
4. Container command in the deployment.yaml djl-serving -m /data/flanT5
5. Load test with Apache Jmeter scripts

## What have you tried to solve it?

1. Replace the entry point script for deepspeed with latest from the main branch
2. Use hugging face entry point script

**Comment by prgawade** [comment]
Additional logs

ai.djl.translate.TranslateException: Batch output size mismatch, expected: 2, actual: 1 
	at ai.djl.python.engine.PyPredictor.batchPredict(PyPredictor.java:95) ~[python-0.22.1.jar:?] 
	at ai.djl.serving.wlm.WorkerThread.run(WorkerThread.java:97) ~[wlm-0.22.1.jar:?] 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?] 
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?] 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?] 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?] 
	at java.lang.Thread.run(Thread.java:829) ~[?:?] 
  HTTP 400 Bad Request

**Comment by frankfliu** [comment]
@prgawade 
Currently the built-in deepspeed handler doesn't support dynamic server side batching. You need to create your own `model.py` to handle batch input. see example: https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/src/test/resources/resnet18/model.py#L89-L110

We will add dynamic batch for all built-in handlers in future release

**Comment by kaustubhrm** [comment]
can you provide this batching mechanism for built-in handler provided for stable diffusion as well? right now I dont see it.
